WARNINGS := -Wall -Wextra -pedantic -Wshadow -Wpointer-arith -Wcast-align \
            -Wwrite-strings -Wmissing-prototypes -Wmissing-declarations \
            -Wredundant-decls -Wnested-externs -Winline -Wno-long-long \
            -Wuninitialized -Wconversion -Wstrict-prototypes -Werror
CFLAGS := -m32 -std=c99 -nostdlib -fno-builtin -nostartfiles -nodefaultlibs -ffreestanding $(WARNINGS)
